# Use the official Python 3 base image
FROM python:3-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project into the container's working directory
COPY . .

# Default command: run the hello.py script
CMD [ "python", "./hello.py" ]
